apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth # this name is only important for logging purposes
          image: oopdaddy/auth
          #          image: us.gcr.io/ticketing-dev-425001/auth
          env:
            - name: JWT_KEY # this is the name viz we are able to get in the auth service
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
