apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args: # to provide to the primary command that gets executed when a container is built out of our image ref: https://hub.docker.com/_/nats-streaming
            [
              '-p',
              '4222',
              '-m',
              '8222', # hb stands for heartbeat
              '-hbi', # hbi => how often that streaming server is going to make a heartbeat request to each of its client
              '5s',
              '-hbt', # hbt => is how long each client has to response
              '5s',
              '-hbf', # hbf is the number of time each client can fail before that streaming server is going to assume that the connection is dead and gone
              '2',
              '-SD',
              '-cid',
              'ticketing',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
