# This GitHub Actions workflow automates the deployment of the auth service.
# It builds the Docker image, pushes it to the Docker registry, and redeploys the service on the Kubernetes cluster.

# Define the name of the workflow as it appears in the Actions UI.
name: deploy-auth

# Configure the event that triggers this workflow.
on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch.
    paths:
      - 'auth/**' # Trigger only when files in the auth directory change.

jobs:
  build: # Define a job named 'build'.
    runs-on: ubuntu-latest # Use the latest Ubuntu runner provided by GitHub Actions.
    steps:
      - uses: actions/checkout@v2
        # Check out your repository so the workflow has access to its content.
      - run: cd auth && docker build -t oopdaddy/auth .
        # Change to the auth directory and build a Docker image tagged 'oopdaddy/auth'.
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        # Log in to Docker registry using credentials from secrets; required to push the image.
      - run: docker push oopdaddy/auth
        # Push the built Docker image to your Docker registry.
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        # Use the doctl action to interact with DigitalOcean; the token authenticates API requests.
      - run: doctl kubernetes cluster kubeconfig save ticketing
        # Save the Kubernetes cluster configuration for 'ticketing' to use with kubectl.
      - run: kubectl rollout restart deployment auth-depl
        # Restart the Kubernetes deployment 'auth-depl' to roll out the new Docker image.
